services:
  - type: web
    name: polev
    env: node
    buildCommand: npm install && npx puppeteer browsers install chrome && npm run build
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
      - key: NODE_VERSION
        value: 20.18.0
